### ISSUE TITLE
create new list > add conacts to the list >save

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#17]
The system adds only one contact to the list . see attached.

![selection_012](https://cloud.githubusercontent.com/assets/13828210/9711759/c017f434-5563-11e5-875a-807f67f36947.png)

![selection_013](https://cloud.githubusercontent.com/assets/13828210/9711762/c6d7ac6a-5563-11e5-95f6-0503d3d3396e.png)

![selection_014](https://cloud.githubusercontent.com/assets/13828210/9711784/f9c3dd24-5563-11e5-90ab-34d1b1ff0a11.png)

**Comment by NishantUpadhyay-BTC** [comment]
I have update the changes and deployed to 'll-botree'. You can test it now.
