### ISSUE TITLE
my accounts >set status > deceased to alive 

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#18]
1. pop up message should not be shown

2. And on clicking save ,The system displays error.

![4](https://cloud.githubusercontent.com/assets/13828210/9715832/cfc6100a-5581-11e5-970a-ff443e08939c.png)

**Comment by SubhashShah-BTC** [comment]
@nikitashah027, This is fixed and deployed.
