### ISSUE TITLE
My Account >> Findings by client

### ISSUE THREAD

**Issue by SubhashShah-BTC** [BoTreeConsultingTeam/life-linker-issues#24]
- [x] Please change field label from ‘Confirm password’ to ‘Confirm new password’.
- [x] Please have prompt appear alongside password field when entering new password that explains the requirement for seven characters, etc, the same as on the new member signup page, etc.
- [x] Note, on the top menu, clicking anywhere on the person’s name should activate the drop down box, not just clicking on the drop down arrow.  The behavior works correctly on the other items, but not on this one.
- [x] Not a bug – we have now decided neither the notifications nor the messages icons will have drop down arrows.  Please remove from the notification icon.
- [x] The drop down menu from the user’s name needs a Logout option
- [x] We would like the multiple-reason checking for reasons why a person is resigning, please.

**Comment by SubhashShah-BTC** [comment]
@nikitashah027 : 

Once deployed, can you please verify the above items? They are mainly UI changes.

**Comment by nikitashah027** [comment]
verified.
