### ISSUE TITLE
profile >> basic information >> birthday >> add Month but do not add other fields(day or year)

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#28]
The system displays error "ActiveRecord::ConnectionTimeoutError"

https://ll-botree.herokuapp.com/users/nikita-shah

![2015-09-17_11-19-22 4](https://cloud.githubusercontent.com/assets/13828210/9925928/635a44cc-5d2e-11e5-8e58-dad135c3dcd2.png)
![2015-09-17_11-16-39 3](https://cloud.githubusercontent.com/assets/13828210/9925932/6bd84f86-5d2e-11e5-93cf-352dd965a2b9.png)

**Comment by NishantUpadhyay-BTC** [comment]
This issue raised because of DB connection on heroku. I have restarted Heroku and it's gone. Please verify it from your end.

**Comment by nikitashah027** [comment]
Not showing this error now.
