### ISSUE TITLE
profile >> basic information >>city of birth

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#32]
In 1st field that is dropdown for selecting a country

Type any letter suppose " I "

It does not take to the countries starting with letter "I"
![2015-09-17_11-57-50 8](https://cloud.githubusercontent.com/assets/13828210/9926482/75e6e5be-5d33-11e5-8736-0cd4e60714fb.png)

**Comment by NishantUpadhyay-BTC** [comment]
@nikitashah027 This is the default behaviour of Bootstrap selectpicker. It searches for occurrence of your searched text in anywhere in the available list. So this is not a bug and you can close it.

**Comment by nikitashah027** [comment]
closed as per the comment.
