### ISSUE TITLE
profile >> all forms >>placeholder 

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#38]
![2015-09-17_12-49-44 15](https://cloud.githubusercontent.com/assets/13828210/9927270/ceb83196-5d3a-11e5-9de9-ce23ea51831a.png)

**Comment by NishantUpadhyay-BTC** [comment]
@nikitashah027  Place-holders are as per PSDs. This is not a bug. You can close it.

**Comment by nikitashah027** [comment]
closed as per the comment.
