### ISSUE TITLE
User activation validation error

### ISSUE THREAD

**Issue by SubhashShah-BTC** [BoTreeConsultingTeam/life-linker-issues#40]
**Steps to reproduce:**
- User registers himself on home page
- User receives an email
- User receives an activation email (run rake account_activations task)
- User clicks on `Activate` link
- Welcome popup will open up with User profile entry form
- User clicks "Continue" without filling any detail.
- User is redirected to new `Basic Information` page with errors.

**Expected Result:**
- User should see the same popup with errors.

**Comment by SubhashShah-BTC** [comment]
This is fixed.

@NishantUpadhyay-BTC : I have pushed it in the `design-member-list-feature.master` branch. Please deploy it when other issues are fixed.

**Comment by nikitashah027** [comment]
verified.
