### ISSUE TITLE
profile >> basic information >>View your profile as if you were (dropdown)

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#41]
1 select basic information from LHS

2. select "as a contact" from the dropdown  of "View your profile as if you were "
 
3. the system shows no response.

**Comment by NishantUpadhyay-BTC** [comment]
@nikitashah027  There is no need of this select box on this page. I have removed it.

**Comment by nikitashah027** [comment]
verified.
