### ISSUE TITLE
Overview page >> As contact >> Edit/Delete links are displayed for current location

### ISSUE THREAD

**Issue by SubhashShah-BTC** [BoTreeConsultingTeam/life-linker-issues#48]
Edit/Delete links are displayed on hover for current location when I view it as contact.

![my-profile-as-contact](https://cloud.githubusercontent.com/assets/5591551/9931088/1d64b1e6-5d56-11e5-9f69-ab6ba826b334.png)

**Comment by nikitashah027** [comment]
@NishantUpadhyay-BTC  Also for primary phone number .
