### ISSUE TITLE
overview page >> spacing issue

### ISSUE THREAD

**Issue by nikitashah027** [BoTreeConsultingTeam/life-linker-issues#57]
Expected

![2015-09-18_12-30-35 5](https://cloud.githubusercontent.com/assets/13828210/9953757/418f2d34-5e01-11e5-9700-a629299c7c0b.png)

**Comment by NishantUpadhyay-BTC** [comment]
@nikitashah027 This middle div is not fixed in size it can grow or shrink based on the details available. So we can not fix it from bottom. You can close this issue.
